repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.278
    hooks:
      - id: ruff
        types_or: [python, pyi]
        args:
          [
            --extend-select,
            I,
            --fix,
            --exit-non-zero-on-fix,
            --line-length,
            "120",
            --ignore,
            E402,
          ]
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        args: [--line-length, "120"]
